### ISSUE TITLE
FDP v2.0.0-PRE1 Crash

### ISSUE THREAD

**Issue by specul4r** [UnlegitMC/FDPClient#271]
I have recently downloaded FDP v2.0.0-PRE1 and it always crashes on launch. Why? also how do i fix it?

Error:
The game crashed whilst initializing game
Error: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Exit-Code: -1

**Comment by kytoff** [comment]
:(

**Comment by liulihaocai** [comment]
fixed

**Comment by specul4r** [comment]
download from getfdp.today? because the client from there still crashes (same error code)

**Comment by liulihaocai** [comment]
> download from getfdp.today? because the client from there still crashes (same error code)

no, download from https://github.com/UnlegitMC/FDPClient/actions/runs/1207373991

**Comment by specul4r** [comment]
i open the client, and after a few seconds it just closes itself - i dont have any other mod except autotip in my forge mod folder, am i supposed to remove automod?
